# Generated by Django 4.0.4 on 2022-07-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_address', models.CharField(max_length=255)),
                ('emp_age', models.IntegerField()),
                ('emp_gender', models.CharField(max_length=255)),
                ('emp_mobile', models.IntegerField()),
                ('emp_photo', models.ImageField(null=True, upload_to='image/')),
                ('join_date', models.DateField()),
            ],
        ),
    ]
