# Generated by Django 4.0.4 on 2022-07-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apppetrol', '0002_category_product_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuel_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelprice', models.IntegerField()),
            ],
        ),
    ]
